general {
    # Optional but useful if you ever suspend: wake displays without double keypress
    after_sleep_cmd = 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 1200 # 20 minutes
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume  = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}