general {
  hide_cursor = true
}

background {
  monitor = 
  color = rgba(0, 0, 0, 0.6) 
  path = /home/fred/Pictures/Backgrounds/Anime/lofi1.jpeg
}

input-field { 
  monitor = HDMI-A-2
  size = 20%, 5%
  outline_thickness = 1

  inner_color = rgba(16, 16, 16, 0.8)
  outer_color = rgba(ffff00ff)
  check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
  fail_color = rgba(ff0000ff)

  font_color = rgb(143, 143, 143)
  font_family = SF Pro Display Bold
  placeholder_text = Passcode
  fade_on_empty = false
  rounding = 16

  position = 100, 80
  halign = left
  valign = bottom
}

label {
  monitor = HDMI-A-2
  # Sat 01 Feb 18:00:01
  text = cmd[update:1000] echo "$(date +"%a %d %b %H:%M:%S")"
  font_size = 24
  font_color = rgb(255, 255, 255)
  font_family = SF Pro Display Bold
  position = 1500, 90
  halign = left
  valign = bottom
}
