# Disable splash text rendering over the wallpaper
splash = false

wallpaper {
  monitor = HDMI-A-1
  path = /home/fred/Pictures/Backgrounds/ford-eskort.jpg
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-2
  path = /home/fred/Pictures/Backgrounds/ford-eskort.jpg
  fit_mode = cover
}