hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  -- hl.exec_cmd("waybar")
  hl.exec_cmd("quickshell -c taskbar")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("solaar --window=hide")
  -- hl.exec_cmd("openrgb --startminimized --profile Fred")
  hl.exec_cmd("hyprpm reload")
end)